### ISSUE TITLE
Failed to build

### ISSUE THREAD

**Issue by Rottweiler** [BahNahNah/NetCore#1]
The assembly failed to build. Message:
```
Failed.
Member 'System.Void.Xor(System.Byte[])' is declared in another module and needs to be imported
```

Code:
```
public static class Crypto
{
    [RemoteMove]
    public static void Xor(byte[] data)
    {
        byte[] Key = GetKey();
        for (int i = 0; i < data.Length; i++)
            data[i] ^= (Key[i % Key.Length]);
    }

    [RemoteMove]
    private static byte[] GetKey()
    {
        return new byte[] { 0x38, 0x9D, 0x24, 0x25, 0x59, 0x24, 0x90, 0x3D, 0xFF };
    }
}

**Comment by Rottweiler** [comment]
And if I make it [RemoteCall] it compiles fine but throws this error:
```
Unhandled Exception: System.InvalidProgramException: Common Language Runtime detected an invalid program.
   at Crypto.Xor(Byte[] data)
   at SecureApp.Program.Main(String[] args)
